### ISSUE TITLE
OpenAPI generation

### ISSUE THREAD

**Issue by cbornet** [agoncal/agoncal-formation-microservices#1]
Follow up on https://twitter.com/agoncal/status/1047052937682403328

**Comment by cbornet** [comment]
So to be sure : do you want to generate the API skeleton for the store service ? Or a client to consume the generator service ?

**Comment by cbornet** [comment]
Both are possible but from the look of the pom, I guess it's the 2nd one, right ?

**Comment by agoncal** [comment]
@cbornet I want the Store service to consume the Generator API. So I want to generate a client to consume the generator API

**Comment by cbornet** [comment]
OK. The `spring` generator without `library` option is a server side generator. To generate a client you have the choice between : openfeign, google-api-client, jersey 1 & 2, okhttp, retrofit, resteasy, Spring RestTemplate, Spring WebClient and Spring-Cloud-Feign.
If you're doing a micro-service arch with service discovery, client-side balancing, circuit-breaker, etc...in a Spring environment, I would recommend using the Spring-Cloud-Feign client.

**Comment by cbornet** [comment]
I'm preparing a PR

**Comment by agoncal** [comment]
Yes, exactly, I want a Feign client. 

Thanks for the PR @cbornet ! Really appreciate #BeerInside

**Comment by cbornet** [comment]
Arf ! There's actually a dependency conflict because spring cloud now uses openfeign... I've fixed that in the [jhipster module](https://github.com/cbornet/generator-jhipster-swagger-cli/blob/master/generators/app/templates/swagger-codegen/libraries/spring-cloud/apiClient.mustache) but it seems I forgot to push the fix to openapi-generator.
So the possibilities are:
* wait that I fix OpenAPI-generator and that it gets into a release
* include a custom template in store-api sources
* downgrade all the project to Spring Boot 1 to be compatible with spring-cloud Dalston

**Comment by cbornet** [comment]
> Yes, exactly, I want a Feign client.

Simple Feign or Spring-Cloud `@FeignClient` one ?

**Comment by agoncal** [comment]
I need `@FeignClient`

Well, if you can fix OpenAPI-generator in the coming days, that would be nice ;o)

**Comment by cbornet** [comment]
Next OpenAPI-generator version (3.3.1) should be released in [2 weeks](https://github.com/OpenAPITools/openapi-generator/milestone/14). I will have done the fix by then.
Meanwhile, I've done a PR with the custom template. That should unblock you until a cleaner solution is provided.

**Comment by agoncal** [comment]
Thanks, works like a charm. 

I'll also give a try when 3.3.1 is released and let you know.
